#!/usr/bin/env node
/**
 * Generate internal/STOCK_FOOTAGE_SHOTLIST.md from the app's own technique data.
 *
 *   node scripts/technique-clips/stock/shotlist.js            # writes the file
 *   node scripts/technique-clips/stock/shotlist.js --stdout   # prints instead
 *
 * One row per own technique entry (ExerciseForm + TechniqueCard), grouped by
 * body part in the order constants/exerciseLibrary.ts lists them. Everything in
 * a row comes from constants/*.ts — edit the data there, then re-run this.
 */
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { loadTechniqueData } = require('./tsload');
const { REPO_ROOT } = require('./lib');

const OUT_FILE = path.join(REPO_ROOT, 'internal', 'STOCK_FOOTAGE_SHOTLIST.md');
const TARGET_VERSION = 2; // v1 = the pictogram baseline; real footage lands as v2

const norm = (s) => String(s ?? '').toLowerCase().replace(/[-_]/g, ' ').replace(/\s+/g, ' ').trim();

/**
 * Entries that live only in the expert programs (not the workout library) are
 * filed by the muscle the program day trains; everything else is looked up by
 * name/alias in the library. Extend this when a new card has no library row.
 */
const EXPERT_ONLY_GROUP = {
  goblet_squat: 'legs',
  seated_barbell_press: 'shoulders',
  rotating_db_press: 'shoulders',
  reverse_pec_deck: 'shoulders',
  barbell_shrug: 'back',
  seated_leg_curl: 'legs',
  tibialis_raise: 'calves',
};

const VIEW_LABEL = { side: 'Side', front: 'Front', front_45: 'Front 45°' };
const VIEW_LOOK = { side: 'side-on (camera square to the lifter\'s side)', front: 'straight on from the front', front_45: '30–45° off the front' };
const POSTURE_LOOK = {
  standing: 'standing',
  seated: 'seated',
  lying: 'lying on the back',
  prone: 'face down / chest supported',
  hanging: 'hanging',
  kneeling: 'kneeling',
  hinged: 'hinged at the hips',
};

/** 'full body' when the camera note asks for the whole body, else the note's own framing. */
function framingFrom(note) {
  const n = norm(note);
  if (n.includes('whole body')) return 'full body';
  const m = /,\s*([^,]+?)\s+in frame\s*$/i.exec(String(note ?? ''));
  if (m) return m[1].trim().replace(/^both /, 'both ');
  return 'head to hips';
}

function lookFor(e) {
  const view = VIEW_LOOK[e.cameraAngle] ?? e.cameraAngle;
  const posture = POSTURE_LOOK[e.posture] ?? e.posture;
  const framing = framingFrom(e.cameraNote);
  return `Shot ${view}, lifter ${posture}, ${framing} in frame; no cuts, camera static.`;
}

function groupFor(e, libIndex) {
  for (const name of [e.exerciseName, ...e.aliases]) {
    const g = libIndex.get(norm(name));
    if (g) return g;
  }
  return EXPERT_ONLY_GROUP[e.id] ?? 'other';
}

const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');

function buildRows(entries, library) {
  const libIndex = new Map();
  for (const g of library) for (const x of g.exercises) libIndex.set(norm(x.name), g.id);
  const groups = [...library.map((g) => ({ id: g.id, label: g.label })), { id: 'other', label: 'Other (expert programs)' }];
  const byGroup = new Map(groups.map((g) => [g.id, []]));
  for (const e of entries) byGroup.get(groupFor(e, libIndex)).push(e);
  return groups.map((g) => ({ ...g, rows: byGroup.get(g.id) }));
}

function renderTable(rows) {
  const head = ['id', 'Display name', 'Aliases', 'View', 'Posture', 'Camera note (from the app)', 'What to look for', 'Length / reps / cut', 'Target file', 'Licensed'];
  const lines = [`| ${head.join(' | ')} |`, `|${head.map(() => '---').join('|')}|`];
  for (const e of rows) {
    lines.push(`| ${[
      `\`${e.id}\``,
      cell(e.exerciseName),
      cell(e.aliases.join(', ') || '—'),
      VIEW_LABEL[e.cameraAngle] ?? e.cameraAngle,
      e.posture,
      cell(e.cameraNote || '—'),
      cell(lookFor(e)),
      '8–12 s, 2–3 clean reps, cut at the TOP position so it loops',
      `\`${e.id}_v${TARGET_VERSION}.mp4\``,
      '[ ]',
    ].join(' | ')} |`);
  }
  return lines.join('\n');
}

function render(data) {
  const groups = buildRows(data.entries, data.library);
  const total = data.entries.length;
  const nForms = data.entries.filter((e) => e.source === 'form').length;
  const nCards = total - nForms;
  const out = [];
  out.push('# Stock footage shot list');
  out.push('');
  out.push('<!-- GENERATED by scripts/technique-clips/stock/shotlist.js from constants/exerciseFormLibrary.ts + constants/techniqueCards.ts. Do not edit by hand — re-run the generator. -->');
  out.push('');
  out.push(`${total} clips to source (${nForms} ExerciseForm entries + ${nCards} technique cards), one per own technique id. The id is final: it is the clip filename stem and the tutorial-memory key. Body-part groups follow the workout library's order.`);
  out.push('');
  out.push('Every clip: **1280×720, 30 fps, no audio, 8–12 s, 2–3 clean reps, start and end at the TOP (rest) position** so the player can loop it. Real footage is uploaded as `_v2` next to the `_v1` pictogram; the app picks the highest version from `manifest.json`, old builds keep playing `_v1`.');
  out.push('');
  out.push('## LICENSE CHECKLIST');
  out.push('');
  out.push('Tick every line for every clip **before** buying. A clip that fails one line is not usable, however good it looks.');
  out.push('');
  out.push('- [ ] **Distribution inside a mobile app is allowed** — the license must cover embedding in an app distributed to end users, with unlimited installs or a cap at least as high as the plan\'s install ceiling. "Web use" or "social media" alone is not enough.');
  out.push('- [ ] **Perpetual and royalty-free** — no renewal, no per-view or per-install fee, no expiry when the subscription lapses (check what happens to clips already used if the provider account is closed).');
  out.push('- [ ] **No attribution requirement** — or, if attribution is required, it is acceptable to show it under Settings → Licenses and the exact credit line is recorded.');
  out.push('- [ ] **Not editorial-only** — editorial licenses forbid commercial use; the app is a paid product.');
  out.push('- [ ] **Model release present** for every recognisable person (face, distinctive tattoos). Providers mark this per item — look for "model released".');
  out.push('- [ ] **No visible brand logos or trademarks** — gym signage, equipment badges, apparel logos, shoe marks. Crop or blur if the license allows derivative edits; otherwise skip the clip.');
  out.push('- [ ] **No music or third-party audio** — we strip audio anyway, but the license must not depend on the soundtrack.');
  out.push('- [ ] **Keep the license receipt per clip** — save the invoice/license PDF, and record the license id in `scripts/technique-clips/out/stock/LICENSES.csv` next to the prepared clips (`out/` is gitignored — back it up with the receipts) with the columns: `id, provider, item id, license type, date`.');
  out.push('');
  out.push('```csv');
  out.push('id,provider,item id,license type,date');
  out.push('deadlift,<provider>,<item id>,<standard|extended|enhanced …>,2026-01-31');
  out.push('```');
  out.push('');
  out.push('## HOW TO');
  out.push('');
  out.push('All commands run from the repo root. Requires ffmpeg/ffprobe (WinGet install is found automatically) and a linked Supabase CLI on PATH. Nothing here needs `npm install`.');
  out.push('');
  out.push('1. **Prep** — trim, crop to 16:9, scale to 1280×720 @ 30 fps, encode with the production recipe, verify, and write a 6×2 contact sheet:');
  out.push('');
  out.push('   ```sh');
  out.push('   node scripts/technique-clips/stock/prep.js deadlift "C:/footage/deadlift-raw.mp4" --start 3.2 --end 12.8');
  out.push('   #   → scripts/technique-clips/out/stock/deadlift_v2.mp4 + out/stock/sheets/deadlift_v2.png');
  out.push('   #   --crop W:H:X:Y  pick a different 16:9 window than the centre');
  out.push('   #   --version N     override the version number (default 2, or bucket max + 1 with --upload)');
  out.push('   ```');
  out.push('');
  out.push('   Open the contact sheet: the 12 tiles must read as the exercise, tile 1 and tile 12 in the same top position.');
  out.push('');
  out.push('2. **Upload** — re-run with `--upload`; it picks the next free version from the bucket, refuses to overwrite an existing object, uploads with the relative path the CLI needs, then republishes the manifest:');
  out.push('');
  out.push('   ```sh');
  out.push('   node scripts/technique-clips/stock/prep.js deadlift "C:/footage/deadlift-raw.mp4" --start 3.2 --end 12.8 --upload');
  out.push('   # equivalent to, after the encode:');
  out.push('   #   supabase storage cp scripts/technique-clips/out/stock/deadlift_v2.mp4 ss:///tutorial-clips/deadlift_v2.mp4 --experimental --content-type video/mp4');
  out.push('   #   node scripts/technique-clips/stock/manifest.js --publish');
  out.push('   ```');
  out.push('');
  out.push('3. **Manifest** — lists the bucket, computes the highest version per id, writes `out/stock/manifest.json`, prints the diff against the previous local one; `--publish` uploads it as `ss:///tutorial-clips/manifest.json` (the one object that is overwritten in place):');
  out.push('');
  out.push('   ```sh');
  out.push('   node scripts/technique-clips/stock/manifest.js            # dry: write + diff only');
  out.push('   node scripts/technique-clips/stock/manifest.js --publish  # + upload manifest.json');
  out.push('   ```');
  out.push('');
  out.push('Versions are immutable: never re-upload an existing `<id>_v<N>.mp4` (clients and the CDN cache by URL) — fix the clip and ship it as the next version.');
  out.push('');
  out.push('## Shot list');
  out.push('');
  for (const g of groups) {
    if (!g.rows.length) continue;
    out.push(`### ${g.label} (${g.rows.length})`);
    out.push('');
    out.push(renderTable(g.rows));
    out.push('');
  }
  return out.join('\n');
}

function main() {
  const data = loadTechniqueData();
  const md = render(data);
  if (process.argv.includes('--stdout')) {
    process.stdout.write(md);
    return;
  }
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, md, 'utf8');
  console.log(`wrote ${path.relative(REPO_ROOT, OUT_FILE)} — ${data.entries.length} rows`);
}

if (require.main === module) main();

module.exports = { render, buildRows, framingFrom, lookFor };
