/**
 * withGradleMemory — persist local-build memory settings across prebuilds.
 *
 * android/gradle.properties is gitignored and regenerated by `expo prebuild`,
 * so hand-tuned values get wiped. Local release builds of this app (heavy
 * native deps: vision-camera, tflite, skia, worklets, health-connect) crash the
 * Gradle JVM with the defaults:
 *   - 2 GB heap → heap OutOfMemory during resource processing
 *   - 6 GB heap + parallel → native OutOfMemory (too many concurrent JVMs+clang)
 * The stable config (15.7 GB dev machine): 4 GB heap, parallel OFF, ≤2 workers.
 *
 * This plugin writes those into gradle.properties on every prebuild so the
 * setup survives. Doesn't affect EAS cloud builds (they have their own runners).
 */
const { withGradleProperties } = require('@expo/config-plugins');

const PROPS = {
  'org.gradle.jvmargs': '-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8',
  'org.gradle.parallel': 'false',
  'org.gradle.workers.max': '2',
};

module.exports = function withGradleMemory(config) {
  return withGradleProperties(config, (config) => {
    const props = config.modResults;
    for (const [key, value] of Object.entries(PROPS)) {
      const existing = props.find((p) => p.type === 'property' && p.key === key);
      if (existing) existing.value = value;
      else props.push({ type: 'property', key, value });
    }
    return config;
  });
};
